/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheaterRouteImport } from './routes/theater'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheaterTheaterSlugRouteImport } from './routes/theater.$theaterSlug'
import { Route as OnboardingTheaterRouteImport } from './routes/onboarding.theater'
import { Route as JoinInviteTokenRouteImport } from './routes/join.$inviteToken'
import { Route as JoinLinkJoinTokenRouteImport } from './routes/join-link.$joinToken'
import { Route as DevComponentsRouteImport } from './routes/dev.components'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppCallsheetRouteImport } from './routes/app.callsheet'
import { Route as AppTheaterSlugRouteImport } from './routes/app.$theaterSlug'
import { Route as TheaterTheaterSlugEventSlugRouteImport } from './routes/theater.$theaterSlug.$eventSlug'
import { Route as AppTheaterSlugSettingsRouteImport } from './routes/app.$theaterSlug.settings'
import { Route as AppTheaterSlugPreviewRouteImport } from './routes/app.$theaterSlug.preview'
import { Route as AppTheaterSlugMembersRouteImport } from './routes/app.$theaterSlug.members'
import { Route as AppTheaterSlugEventsRouteImport } from './routes/app.$theaterSlug.events'
import { Route as AppTheaterSlugEventsNewRouteImport } from './routes/app.$theaterSlug.events.new'
import { Route as AppTheaterSlugEventsEventSlugRouteImport } from './routes/app.$theaterSlug.events.$eventSlug'

const TheaterRoute = TheaterRouteImport.update({
  id: '/theater',
  path: '/theater',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheaterTheaterSlugRoute = TheaterTheaterSlugRouteImport.update({
  id: '/$theaterSlug',
  path: '/$theaterSlug',
  getParentRoute: () => TheaterRoute,
} as any)
const OnboardingTheaterRoute = OnboardingTheaterRouteImport.update({
  id: '/theater',
  path: '/theater',
  getParentRoute: () => OnboardingRoute,
} as any)
const JoinInviteTokenRoute = JoinInviteTokenRouteImport.update({
  id: '/join/$inviteToken',
  path: '/join/$inviteToken',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinLinkJoinTokenRoute = JoinLinkJoinTokenRouteImport.update({
  id: '/join-link/$joinToken',
  path: '/join-link/$joinToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCallsheetRoute = AppCallsheetRouteImport.update({
  id: '/callsheet',
  path: '/callsheet',
  getParentRoute: () => AppRoute,
} as any)
const AppTheaterSlugRoute = AppTheaterSlugRouteImport.update({
  id: '/$theaterSlug',
  path: '/$theaterSlug',
  getParentRoute: () => AppRoute,
} as any)
const TheaterTheaterSlugEventSlugRoute =
  TheaterTheaterSlugEventSlugRouteImport.update({
    id: '/$eventSlug',
    path: '/$eventSlug',
    getParentRoute: () => TheaterTheaterSlugRoute,
  } as any)
const AppTheaterSlugSettingsRoute = AppTheaterSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTheaterSlugRoute,
} as any)
const AppTheaterSlugPreviewRoute = AppTheaterSlugPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppTheaterSlugRoute,
} as any)
const AppTheaterSlugMembersRoute = AppTheaterSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppTheaterSlugRoute,
} as any)
const AppTheaterSlugEventsRoute = AppTheaterSlugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppTheaterSlugRoute,
} as any)
const AppTheaterSlugEventsNewRoute = AppTheaterSlugEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTheaterSlugEventsRoute,
} as any)
const AppTheaterSlugEventsEventSlugRoute =
  AppTheaterSlugEventsEventSlugRouteImport.update({
    id: '/$eventSlug',
    path: '/$eventSlug',
    getParentRoute: () => AppTheaterSlugEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/theater': typeof TheaterRouteWithChildren
  '/app/$theaterSlug': typeof AppTheaterSlugRouteWithChildren
  '/app/callsheet': typeof AppCallsheetRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/components': typeof DevComponentsRoute
  '/join-link/$joinToken': typeof JoinLinkJoinTokenRoute
  '/join/$inviteToken': typeof JoinInviteTokenRoute
  '/onboarding/theater': typeof OnboardingTheaterRoute
  '/theater/$theaterSlug': typeof TheaterTheaterSlugRouteWithChildren
  '/app/$theaterSlug/events': typeof AppTheaterSlugEventsRouteWithChildren
  '/app/$theaterSlug/members': typeof AppTheaterSlugMembersRoute
  '/app/$theaterSlug/preview': typeof AppTheaterSlugPreviewRoute
  '/app/$theaterSlug/settings': typeof AppTheaterSlugSettingsRoute
  '/theater/$theaterSlug/$eventSlug': typeof TheaterTheaterSlugEventSlugRoute
  '/app/$theaterSlug/events/$eventSlug': typeof AppTheaterSlugEventsEventSlugRoute
  '/app/$theaterSlug/events/new': typeof AppTheaterSlugEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/theater': typeof TheaterRouteWithChildren
  '/app/$theaterSlug': typeof AppTheaterSlugRouteWithChildren
  '/app/callsheet': typeof AppCallsheetRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/components': typeof DevComponentsRoute
  '/join-link/$joinToken': typeof JoinLinkJoinTokenRoute
  '/join/$inviteToken': typeof JoinInviteTokenRoute
  '/onboarding/theater': typeof OnboardingTheaterRoute
  '/theater/$theaterSlug': typeof TheaterTheaterSlugRouteWithChildren
  '/app/$theaterSlug/events': typeof AppTheaterSlugEventsRouteWithChildren
  '/app/$theaterSlug/members': typeof AppTheaterSlugMembersRoute
  '/app/$theaterSlug/preview': typeof AppTheaterSlugPreviewRoute
  '/app/$theaterSlug/settings': typeof AppTheaterSlugSettingsRoute
  '/theater/$theaterSlug/$eventSlug': typeof TheaterTheaterSlugEventSlugRoute
  '/app/$theaterSlug/events/$eventSlug': typeof AppTheaterSlugEventsEventSlugRoute
  '/app/$theaterSlug/events/new': typeof AppTheaterSlugEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/theater': typeof TheaterRouteWithChildren
  '/app/$theaterSlug': typeof AppTheaterSlugRouteWithChildren
  '/app/callsheet': typeof AppCallsheetRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/components': typeof DevComponentsRoute
  '/join-link/$joinToken': typeof JoinLinkJoinTokenRoute
  '/join/$inviteToken': typeof JoinInviteTokenRoute
  '/onboarding/theater': typeof OnboardingTheaterRoute
  '/theater/$theaterSlug': typeof TheaterTheaterSlugRouteWithChildren
  '/app/$theaterSlug/events': typeof AppTheaterSlugEventsRouteWithChildren
  '/app/$theaterSlug/members': typeof AppTheaterSlugMembersRoute
  '/app/$theaterSlug/preview': typeof AppTheaterSlugPreviewRoute
  '/app/$theaterSlug/settings': typeof AppTheaterSlugSettingsRoute
  '/theater/$theaterSlug/$eventSlug': typeof TheaterTheaterSlugEventSlugRoute
  '/app/$theaterSlug/events/$eventSlug': typeof AppTheaterSlugEventsEventSlugRoute
  '/app/$theaterSlug/events/new': typeof AppTheaterSlugEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/complete-profile'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/signup'
    | '/theater'
    | '/app/$theaterSlug'
    | '/app/callsheet'
    | '/auth/callback'
    | '/dev/components'
    | '/join-link/$joinToken'
    | '/join/$inviteToken'
    | '/onboarding/theater'
    | '/theater/$theaterSlug'
    | '/app/$theaterSlug/events'
    | '/app/$theaterSlug/members'
    | '/app/$theaterSlug/preview'
    | '/app/$theaterSlug/settings'
    | '/theater/$theaterSlug/$eventSlug'
    | '/app/$theaterSlug/events/$eventSlug'
    | '/app/$theaterSlug/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/complete-profile'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/signup'
    | '/theater'
    | '/app/$theaterSlug'
    | '/app/callsheet'
    | '/auth/callback'
    | '/dev/components'
    | '/join-link/$joinToken'
    | '/join/$inviteToken'
    | '/onboarding/theater'
    | '/theater/$theaterSlug'
    | '/app/$theaterSlug/events'
    | '/app/$theaterSlug/members'
    | '/app/$theaterSlug/preview'
    | '/app/$theaterSlug/settings'
    | '/theater/$theaterSlug/$eventSlug'
    | '/app/$theaterSlug/events/$eventSlug'
    | '/app/$theaterSlug/events/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/complete-profile'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/signup'
    | '/theater'
    | '/app/$theaterSlug'
    | '/app/callsheet'
    | '/auth/callback'
    | '/dev/components'
    | '/join-link/$joinToken'
    | '/join/$inviteToken'
    | '/onboarding/theater'
    | '/theater/$theaterSlug'
    | '/app/$theaterSlug/events'
    | '/app/$theaterSlug/members'
    | '/app/$theaterSlug/preview'
    | '/app/$theaterSlug/settings'
    | '/theater/$theaterSlug/$eventSlug'
    | '/app/$theaterSlug/events/$eventSlug'
    | '/app/$theaterSlug/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignupRoute: typeof SignupRoute
  TheaterRoute: typeof TheaterRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  DevComponentsRoute: typeof DevComponentsRoute
  JoinLinkJoinTokenRoute: typeof JoinLinkJoinTokenRoute
  JoinInviteTokenRoute: typeof JoinInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theater': {
      id: '/theater'
      path: '/theater'
      fullPath: '/theater'
      preLoaderRoute: typeof TheaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theater/$theaterSlug': {
      id: '/theater/$theaterSlug'
      path: '/$theaterSlug'
      fullPath: '/theater/$theaterSlug'
      preLoaderRoute: typeof TheaterTheaterSlugRouteImport
      parentRoute: typeof TheaterRoute
    }
    '/onboarding/theater': {
      id: '/onboarding/theater'
      path: '/theater'
      fullPath: '/onboarding/theater'
      preLoaderRoute: typeof OnboardingTheaterRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/join/$inviteToken': {
      id: '/join/$inviteToken'
      path: '/join/$inviteToken'
      fullPath: '/join/$inviteToken'
      preLoaderRoute: typeof JoinInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-link/$joinToken': {
      id: '/join-link/$joinToken'
      path: '/join-link/$joinToken'
      fullPath: '/join-link/$joinToken'
      preLoaderRoute: typeof JoinLinkJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/callsheet': {
      id: '/app/callsheet'
      path: '/callsheet'
      fullPath: '/app/callsheet'
      preLoaderRoute: typeof AppCallsheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$theaterSlug': {
      id: '/app/$theaterSlug'
      path: '/$theaterSlug'
      fullPath: '/app/$theaterSlug'
      preLoaderRoute: typeof AppTheaterSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/theater/$theaterSlug/$eventSlug': {
      id: '/theater/$theaterSlug/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/theater/$theaterSlug/$eventSlug'
      preLoaderRoute: typeof TheaterTheaterSlugEventSlugRouteImport
      parentRoute: typeof TheaterTheaterSlugRoute
    }
    '/app/$theaterSlug/settings': {
      id: '/app/$theaterSlug/settings'
      path: '/settings'
      fullPath: '/app/$theaterSlug/settings'
      preLoaderRoute: typeof AppTheaterSlugSettingsRouteImport
      parentRoute: typeof AppTheaterSlugRoute
    }
    '/app/$theaterSlug/preview': {
      id: '/app/$theaterSlug/preview'
      path: '/preview'
      fullPath: '/app/$theaterSlug/preview'
      preLoaderRoute: typeof AppTheaterSlugPreviewRouteImport
      parentRoute: typeof AppTheaterSlugRoute
    }
    '/app/$theaterSlug/members': {
      id: '/app/$theaterSlug/members'
      path: '/members'
      fullPath: '/app/$theaterSlug/members'
      preLoaderRoute: typeof AppTheaterSlugMembersRouteImport
      parentRoute: typeof AppTheaterSlugRoute
    }
    '/app/$theaterSlug/events': {
      id: '/app/$theaterSlug/events'
      path: '/events'
      fullPath: '/app/$theaterSlug/events'
      preLoaderRoute: typeof AppTheaterSlugEventsRouteImport
      parentRoute: typeof AppTheaterSlugRoute
    }
    '/app/$theaterSlug/events/new': {
      id: '/app/$theaterSlug/events/new'
      path: '/new'
      fullPath: '/app/$theaterSlug/events/new'
      preLoaderRoute: typeof AppTheaterSlugEventsNewRouteImport
      parentRoute: typeof AppTheaterSlugEventsRoute
    }
    '/app/$theaterSlug/events/$eventSlug': {
      id: '/app/$theaterSlug/events/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/app/$theaterSlug/events/$eventSlug'
      preLoaderRoute: typeof AppTheaterSlugEventsEventSlugRouteImport
      parentRoute: typeof AppTheaterSlugEventsRoute
    }
  }
}

interface AppTheaterSlugEventsRouteChildren {
  AppTheaterSlugEventsEventSlugRoute: typeof AppTheaterSlugEventsEventSlugRoute
  AppTheaterSlugEventsNewRoute: typeof AppTheaterSlugEventsNewRoute
}

const AppTheaterSlugEventsRouteChildren: AppTheaterSlugEventsRouteChildren = {
  AppTheaterSlugEventsEventSlugRoute: AppTheaterSlugEventsEventSlugRoute,
  AppTheaterSlugEventsNewRoute: AppTheaterSlugEventsNewRoute,
}

const AppTheaterSlugEventsRouteWithChildren =
  AppTheaterSlugEventsRoute._addFileChildren(AppTheaterSlugEventsRouteChildren)

interface AppTheaterSlugRouteChildren {
  AppTheaterSlugEventsRoute: typeof AppTheaterSlugEventsRouteWithChildren
  AppTheaterSlugMembersRoute: typeof AppTheaterSlugMembersRoute
  AppTheaterSlugPreviewRoute: typeof AppTheaterSlugPreviewRoute
  AppTheaterSlugSettingsRoute: typeof AppTheaterSlugSettingsRoute
}

const AppTheaterSlugRouteChildren: AppTheaterSlugRouteChildren = {
  AppTheaterSlugEventsRoute: AppTheaterSlugEventsRouteWithChildren,
  AppTheaterSlugMembersRoute: AppTheaterSlugMembersRoute,
  AppTheaterSlugPreviewRoute: AppTheaterSlugPreviewRoute,
  AppTheaterSlugSettingsRoute: AppTheaterSlugSettingsRoute,
}

const AppTheaterSlugRouteWithChildren = AppTheaterSlugRoute._addFileChildren(
  AppTheaterSlugRouteChildren,
)

interface AppRouteChildren {
  AppTheaterSlugRoute: typeof AppTheaterSlugRouteWithChildren
  AppCallsheetRoute: typeof AppCallsheetRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTheaterSlugRoute: AppTheaterSlugRouteWithChildren,
  AppCallsheetRoute: AppCallsheetRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingTheaterRoute: typeof OnboardingTheaterRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingTheaterRoute: OnboardingTheaterRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface TheaterTheaterSlugRouteChildren {
  TheaterTheaterSlugEventSlugRoute: typeof TheaterTheaterSlugEventSlugRoute
}

const TheaterTheaterSlugRouteChildren: TheaterTheaterSlugRouteChildren = {
  TheaterTheaterSlugEventSlugRoute: TheaterTheaterSlugEventSlugRoute,
}

const TheaterTheaterSlugRouteWithChildren =
  TheaterTheaterSlugRoute._addFileChildren(TheaterTheaterSlugRouteChildren)

interface TheaterRouteChildren {
  TheaterTheaterSlugRoute: typeof TheaterTheaterSlugRouteWithChildren
}

const TheaterRouteChildren: TheaterRouteChildren = {
  TheaterTheaterSlugRoute: TheaterTheaterSlugRouteWithChildren,
}

const TheaterRouteWithChildren =
  TheaterRoute._addFileChildren(TheaterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignupRoute: SignupRoute,
  TheaterRoute: TheaterRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  DevComponentsRoute: DevComponentsRoute,
  JoinLinkJoinTokenRoute: JoinLinkJoinTokenRoute,
  JoinInviteTokenRoute: JoinInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
